import os

ROOT_DIR = os.path.abspath(".")  # Current dir (jaicat_project)
LOG_FILE = "init_patch_log.txt"

skipped_dirs = ["__pycache__", ".venv", "env", "venv"]
added_inits = []
existing_inits = []

for root, dirs, files in os.walk(ROOT_DIR):
    if any(skip in root for skip in skipped_dirs):
        continue

    if "__init__.py" not in files:
        try:
            init_path = os.path.join(root, "__init__.py")
            with open(init_path, "w", encoding="utf-8") as f:
                f.write("# Auto-generated by add_missing_inits.py\n")
            added_inits.append(init_path)
        except Exception as e:
            print(f"❌ Could not create __init__.py in {root}: {e}")
    else:
        existing_inits.append(root)

with open(LOG_FILE, "w", encoding="utf-8") as log:
    log.write("====== INIT FILE PATCH LOG ======\n\n")
    log.write("✅ Existing `__init__.py` Found In:\n")
    for d in existing_inits:
        log.write(f"{d}\n")

    log.write("\n✨ `__init__.py` ADDED To:\n")
    for d in added_inits:
        log.write(f"{d}\n")

print(f"✅ Done. Added {len(added_inits)} new `__init__.py` files. Log saved to {LOG_FILE}")
# Ensure the add_missing_inits.py script runs correctly
# This script adds missing __init__.py files to directories in the Jaicat project    
