# Auto-generated by add_missing_inits.py
# services/__init__.py
# Tiny global service registry (simple DI container)

from typing import Any, Dict

_registry: Dict[str, Any] = {}

def register(name: str, instance: Any) -> None:
    _registry[name] = instance

def resolve(name: str) -> Any:
    if name not in _registry:
        raise KeyError(f"Service '{name}' is not registered.")
    return _registry[name]

def has(name: str) -> bool:
    return name in _registry

# Optional: allow `from services import registry` style
class _RegistryView:
    register = staticmethod(register)
    resolve = staticmethod(resolve)
    has = staticmethod(has)

registry = _RegistryView()
